name       : qt5-remoteobjects
version    : 5.15.10
release    : 5
source     :
    - git|https://invent.kde.org/qt/qt/qtremoteobjects.git : d10e7673218fa2b00191a82ad20cd3304a711fa6
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Inter-process communication (IPC) module developed for Qt
description: |
    Qt Remote Objects (QtRO) is an Inter-Process Communication (IPC) module developed for Qt. This module extends Qt's existing functionalities to enable information exchange between processes or computers, easily.
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
